<h1 align="center">Final Project

<h3 align="center">Aprendizagem Probabílista e Reconhecimento de Padrões
<h3 align="center">2022/2023 - 2º Semestre

Imports

In [188]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Data Import

In [189]:
#Load the dataset from the LoanData_Bondora.csv file
dataset = pd.read_csv('LoanData_Bondora.csv')

/var/folders/48/941_svv94h3dxz5s1_jb0wcm0000gn/T/ipykernel_46582/2523053416.py:2: DtypeWarning: Columns (34,38,80,82,83,89,90) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('LoanData_Bondora.csv')

In [190]:
dataset

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,PreviousEarlyRepaymentsCountBeforeLoan,GracePeriodStart,GracePeriodEnd,NextPaymentDate,NextPaymentNr,NrOfScheduledPayments,ReScheduledOn,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost,ActiveLateLastPaymentCategory
0,2021-07-20,66AE108B-532B-4BB3-BAB7-0019A46412C1,483449,2016-03-23 16:07:19,2016-03-23 16:07:19,970,1150,5.0,BO965519,False,...,0.0,2019-10-28,2020-01-27,NaN,NaN,NaN,NaN,0.00,51.73,31-60
1,2021-07-20,D152382E-A50D-46ED-8FF2-0053E0C86A70,378148,2015-06-25 11:02:28,2015-06-25 11:02:28,1295,0,1705.0,BOA9K172A,False,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,47.08,180+
2,2021-07-20,87342E13-66CB-483F-833A-007953E50C78,451831,2016-01-14 10:00:21,2016-01-14 10:00:21,2700,565,5835.0,BO7971663,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,259.67,1659.60,180+
3,2021-07-20,87227056-6BF9-410C-98D1-008F788E122A,349381,2015-03-24 15:55:44,2015-03-24 15:55:44,1115,0,385.0,BO76151K3,True,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,215.05,180+
4,2021-07-20,2DDE6336-E466-4624-A337-00A0ED1A1468,443082,2015-12-17 10:12:00,2015-12-17 10:12:00,305,0,785.0,BOK423A63,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,180+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179230,2021-07-20,D9E714C3-B9B8-4FD1-B1AD-FF55B3AE8A8F,323749,2015-03-02 07:07:05,2015-03-02 07:07:05,2000,0,0.0,BO6492A4A,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,18.38,180+
179231,2021-07-20,09999223-3D69-42E3-BAAA-FF7F312AB236,468598,2016-02-17 10:17:35,2016-02-17 10:17:35,6215,70,1155.0,BO542A57A,False,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN
179232,2021-07-20,370193A5-D19C-4A99-97F7-FF95BEA52731,462572,2016-02-05 09:35:26,2016-02-05 09:35:26,430,0,1055.0,BO65A965,False,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN
179233,2021-07-20,98D9FCCE-0FD7-420E-9F7F-FFA960669E8B,396046,2015-08-17 17:23:05,2015-08-17 17:23:05,3000,0,0.0,BO9577433,True,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN
179234,2021-07-20,65C924CD-8AAF-4ECC-9C8F-FFB0C5722CBB,374840,2015-06-15 10:22:34,2015-06-15 10:22:34,0,0,1300.0,avo1007,False,...,2.0,2016-04-27,2017-04-27,NaN,NaN,NaN,NaN,0.00,2.64,180+

O dataset tem um total de 112 features relativas a cerca de 180k empréstimos. Dentro destas features

In [191]:
# List and Print all the columns in the dataset
columns = list(dataset.columns.values)
columns

['ReportAsOfEOD',
 'LoanId',
 'LoanNumber',
 'ListedOnUTC',
 'BiddingStartedOn',
 'BidsPortfolioManager',
 'BidsApi',
 'BidsManual',
 'UserName',
 'NewCreditCustomer',
 'LoanApplicationStartedDate',
 'LoanDate',
 'ContractEndDate',
 'FirstPaymentDate',
 'MaturityDate_Original',
 'MaturityDate_Last',
 'ApplicationSignedHour',
 'ApplicationSignedWeekday',
 'VerificationType',
 'LanguageCode',
 'Age',
 'DateOfBirth',
 'Gender',
 'Country',
 'AppliedAmount',
 'Amount',
 'Interest',
 'LoanDuration',
 'MonthlyPayment',
 'County',
 'City',
 'UseOfLoan',
 'Education',
 'MaritalStatus',
 'NrOfDependants',
 'EmploymentStatus',
 'EmploymentDurationCurrentEmployer',
 'EmploymentPosition',
 'WorkExperience',
 'OccupationArea',
 'HomeOwnershipType',
 'IncomeFromPrincipalEmployer',
 'IncomeFromPension',
 'IncomeFromFamilyAllowance',
 'IncomeFromSocialWelfare',
 'IncomeFromLeavePay',
 'IncomeFromChildSupport',
 'IncomeOther',
 'IncomeTotal',
 'ExistingLiabilities',
 'LiabilitiesTotal',
 'RefinanceLiabilities',
 'DebtToIncome',
 'FreeCash',
 'MonthlyPaymentDay',
 'ActiveScheduleFirstPaymentReached',
 'PlannedPrincipalTillDate',
 'PlannedInterestTillDate',
 'LastPaymentOn',
 'CurrentDebtDaysPrimary',
 'DebtOccuredOn',
 'CurrentDebtDaysSecondary',
 'DebtOccuredOnForSecondary',
 'ExpectedLoss',
 'LossGivenDefault',
 'ExpectedReturn',
 'ProbabilityOfDefault',
 'DefaultDate',
 'PrincipalOverdueBySchedule',
 'PlannedPrincipalPostDefault',
 'PlannedInterestPostDefault',
 'EAD1',
 'EAD2',
 'PrincipalRecovery',
 'InterestRecovery',
 'RecoveryStage',
 'StageActiveSince',
 'ModelVersion',
 'Rating',
 'EL_V0',
 'Rating_V0',
 'EL_V1',
 'Rating_V1',
 'Rating_V2',
 'Status',
 'Restructured',
 'ActiveLateCategory',
 'WorseLateCategory',
 'CreditScoreEsMicroL',
 'CreditScoreEsEquifaxRisk',
 'CreditScoreFiAsiakasTietoRiskGrade',
 'CreditScoreEeMini',
 'PrincipalPaymentsMade',
 'InterestAndPenaltyPaymentsMade',
 'PrincipalWriteOffs',
 'InterestAndPenaltyWriteOffs',
 'PrincipalBalance',
 'InterestAndPenaltyBalance',
 'NoOfPreviousLoansBeforeLoan',
 'AmountOfPreviousLoansBeforeLoan',
 'PreviousRepaymentsBeforeLoan',
 'PreviousEarlyRepaymentsBefoleLoan',
 'PreviousEarlyRepaymentsCountBeforeLoan',
 'GracePeriodStart',
 'GracePeriodEnd',
 'NextPaymentDate',
 'NextPaymentNr',
 'NrOfScheduledPayments',
 'ReScheduledOn',
 'PrincipalDebtServicingCost',
 'InterestAndPenaltyDebtServicingCost',
 'ActiveLateLastPaymentCategory']

In [192]:
# Print the number of NaN values in each column
for i in dataset.columns:
    print(i,dataset[i].isnull().sum())

ReportAsOfEOD 0
LoanId 0
LoanNumber 0
ListedOnUTC 0
BiddingStartedOn 0
BidsPortfolioManager 0
BidsApi 0
BidsManual 0
UserName 0
NewCreditCustomer 0
LoanApplicationStartedDate 0
LoanDate 0
ContractEndDate 76239
FirstPaymentDate 0
MaturityDate_Original 0
MaturityDate_Last 0
ApplicationSignedHour 0
ApplicationSignedWeekday 0
VerificationType 50
LanguageCode 0
Age 0
DateOfBirth 179235
Gender 45
Country 0
AppliedAmount 0
Amount 0
Interest 0
LoanDuration 0
MonthlyPayment 6690
County 179235
City 179235
UseOfLoan 0
Education 50
MaritalStatus 50
NrOfDependants 143635
EmploymentStatus 202
EmploymentDurationCurrentEmployer 1606
EmploymentPosition 179235
WorkExperience 142713
OccupationArea 91
HomeOwnershipType 1657
IncomeFromPrincipalEmployer 0
IncomeFromPension 0
IncomeFromFamilyAllowance 0
IncomeFromSocialWelfare 0
IncomeFromLeavePay 0
IncomeFromChildSupport 0
IncomeOther 0
IncomeTotal 0
ExistingLiabilities 0
LiabilitiesTotal 0
RefinanceLiabilities 0
DebtToIncome 50
FreeCash 50
MonthlyPaymentDay 0
ActiveScheduleFirstPaymentReached 0
PlannedPrincipalTillDate 124771
PlannedInterestTillDate 1974
LastPaymentOn 6725
CurrentDebtDaysPrimary 103011
DebtOccuredOn 103011
CurrentDebtDaysSecondary 96967
DebtOccuredOnForSecondary 96967
ExpectedLoss 2639
LossGivenDefault 2639
ExpectedReturn 2639
ProbabilityOfDefault 2639
DefaultDate 107819
PrincipalOverdueBySchedule 14843
PlannedPrincipalPostDefault 107820
PlannedInterestPostDefault 107820
EAD1 107821
EAD2 107821
PrincipalRecovery 107820
InterestRecovery 107820
RecoveryStage 67295
StageActiveSince 60488
ModelVersion 2639
Rating 2733
EL_V0 174666
Rating_V0 174666
EL_V1 166311
Rating_V1 166311
Rating_V2 154092
Status 0
Restructured 0
ActiveLateCategory 104251
WorseLateCategory 52329
CreditScoreEsMicroL 30304
CreditScoreEsEquifaxRisk 167016
CreditScoreFiAsiakasTietoRiskGrade 137407
CreditScoreEeMini 74138
PrincipalPaymentsMade 0
InterestAndPenaltyPaymentsMade 0
PrincipalWriteOffs 103085
InterestAndPenaltyWriteOffs 103085
PrincipalBalance 0
InterestAndPenaltyBalance 5232
NoOfPreviousLoansBeforeLoan 9
AmountOfPreviousLoansBeforeLoan 9
PreviousRepaymentsBeforeLoan 62386
PreviousEarlyRepaymentsBefoleLoan 120350
PreviousEarlyRepaymentsCountBeforeLoan 9
GracePeriodStart 137350
GracePeriodEnd 137350
NextPaymentDate 113614
NextPaymentNr 66944
NrOfScheduledPayments 66944
ReScheduledOn 116191
PrincipalDebtServicingCost 103085
InterestAndPenaltyDebtServicingCost 103085
ActiveLateLastPaymentCategory 96967

A lot of columns have almost all its values as NaN meaning that the values are missing or incomplete since they are empty cells. To procceed with the project we will delete some of them so that we have less noise in our analysis.

In [193]:
# Print the names of the columns that have 50% or more NaN values
cols50percentnull = []
for i in dataset.columns:
    if dataset[i].isnull().sum() > 0.5*len(dataset):
        cols50percentnull.append(i)

cols50percentnull

['DateOfBirth',
 'County',
 'City',
 'NrOfDependants',
 'EmploymentPosition',
 'WorkExperience',
 'PlannedPrincipalTillDate',
 'CurrentDebtDaysPrimary',
 'DebtOccuredOn',
 'CurrentDebtDaysSecondary',
 'DebtOccuredOnForSecondary',
 'DefaultDate',
 'PlannedPrincipalPostDefault',
 'PlannedInterestPostDefault',
 'EAD1',
 'EAD2',
 'PrincipalRecovery',
 'InterestRecovery',
 'EL_V0',
 'Rating_V0',
 'EL_V1',
 'Rating_V1',
 'Rating_V2',
 'ActiveLateCategory',
 'CreditScoreEsEquifaxRisk',
 'CreditScoreFiAsiakasTietoRiskGrade',
 'PrincipalWriteOffs',
 'InterestAndPenaltyWriteOffs',
 'PreviousEarlyRepaymentsBefoleLoan',
 'GracePeriodStart',
 'GracePeriodEnd',
 'NextPaymentDate',
 'ReScheduledOn',
 'PrincipalDebtServicingCost',
 'InterestAndPenaltyDebtServicingCost',
 'ActiveLateLastPaymentCategory']

In [194]:
#Count the number of columns that have 50% or more NaN values
count = 0
for i in cols50percentnull:
    count += 1

print(count)

36

In [195]:
#Take out columns with more than 50% null values
dataset = dataset.drop(cols50percentnull, axis=1)
dataset

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan,NextPaymentNr,NrOfScheduledPayments
0,2021-07-20,66AE108B-532B-4BB3-BAB7-0019A46412C1,483449,2016-03-23 16:07:19,2016-03-23 16:07:19,970,1150,5.0,BO965519,False,...,969.16,1187.91,1155.84,433.60,1.0,500.0,590.95,0.0,NaN,NaN
1,2021-07-20,D152382E-A50D-46ED-8FF2-0053E0C86A70,378148,2015-06-25 11:02:28,2015-06-25 11:02:28,1295,0,1705.0,BOA9K172A,False,...,563.59,360.07,2436.41,2291.82,1.0,1800.0,445.26,1.0,NaN,NaN
2,2021-07-20,87342E13-66CB-483F-833A-007953E50C78,451831,2016-01-14 10:00:21,2016-01-14 10:00:21,2700,565,5835.0,BO7971663,True,...,6537.00,1708.47,0.00,0.00,0.0,0.0,0.00,0.0,NaN,NaN
3,2021-07-20,87227056-6BF9-410C-98D1-008F788E122A,349381,2015-03-24 15:55:44,2015-03-24 15:55:44,1115,0,385.0,BO76151K3,True,...,464.73,355.92,1035.27,2833.83,0.0,0.0,0.00,1.0,NaN,NaN
4,2021-07-20,2DDE6336-E466-4624-A337-00A0ED1A1468,443082,2015-12-17 10:12:00,2015-12-17 10:12:00,305,0,785.0,BOK423A63,True,...,0.01,0.00,1089.99,4215.37,0.0,0.0,0.00,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179230,2021-07-20,D9E714C3-B9B8-4FD1-B1AD-FF55B3AE8A8F,323749,2015-03-02 07:07:05,2015-03-02 07:07:05,2000,0,0.0,BO6492A4A,True,...,0.00,0.00,2000.00,4284.86,0.0,0.0,0.00,0.0,NaN,NaN
179231,2021-07-20,09999223-3D69-42E3-BAAA-FF7F312AB236,468598,2016-02-17 10:17:35,2016-02-17 10:17:35,6215,70,1155.0,BO542A57A,False,...,7440.00,2664.67,0.00,0.00,2.0,2500.0,986.78,0.0,NaN,NaN
179232,2021-07-20,370193A5-D19C-4A99-97F7-FF95BEA52731,462572,2016-02-05 09:35:26,2016-02-05 09:35:26,430,0,1055.0,BO65A965,False,...,1485.00,186.41,0.00,0.00,3.0,2425.0,2749.65,1.0,NaN,NaN
179233,2021-07-20,98D9FCCE-0FD7-420E-9F7F-FFA960669E8B,396046,2015-08-17 17:23:05,2015-08-17 17:23:05,3000,0,0.0,BO9577433,True,...,3000.00,1974.70,0.00,0.00,0.0,0.0,0.00,0.0,NaN,NaN
179234,2021-07-20,65C924CD-8AAF-4ECC-9C8F-FFB0C5722CBB,374840,2015-06-15 10:22:34,2015-06-15 10:22:34,0,0,1300.0,avo1007,False,...,475.78,152.98,0.00,0.00,4.0,8000.0,4462.13,2.0,NaN,NaN

In [196]:
#Get column names that are still present in the dataset
columns = list(dataset.columns.values)
columns

['ReportAsOfEOD',
 'LoanId',
 'LoanNumber',
 'ListedOnUTC',
 'BiddingStartedOn',
 'BidsPortfolioManager',
 'BidsApi',
 'BidsManual',
 'UserName',
 'NewCreditCustomer',
 'LoanApplicationStartedDate',
 'LoanDate',
 'ContractEndDate',
 'FirstPaymentDate',
 'MaturityDate_Original',
 'MaturityDate_Last',
 'ApplicationSignedHour',
 'ApplicationSignedWeekday',
 'VerificationType',
 'LanguageCode',
 'Age',
 'Gender',
 'Country',
 'AppliedAmount',
 'Amount',
 'Interest',
 'LoanDuration',
 'MonthlyPayment',
 'UseOfLoan',
 'Education',
 'MaritalStatus',
 'EmploymentStatus',
 'EmploymentDurationCurrentEmployer',
 'OccupationArea',
 'HomeOwnershipType',
 'IncomeFromPrincipalEmployer',
 'IncomeFromPension',
 'IncomeFromFamilyAllowance',
 'IncomeFromSocialWelfare',
 'IncomeFromLeavePay',
 'IncomeFromChildSupport',
 'IncomeOther',
 'IncomeTotal',
 'ExistingLiabilities',
 'LiabilitiesTotal',
 'RefinanceLiabilities',
 'DebtToIncome',
 'FreeCash',
 'MonthlyPaymentDay',
 'ActiveScheduleFirstPaymentReached',
 'PlannedInterestTillDate',
 'LastPaymentOn',
 'ExpectedLoss',
 'LossGivenDefault',
 'ExpectedReturn',
 'ProbabilityOfDefault',
 'PrincipalOverdueBySchedule',
 'RecoveryStage',
 'StageActiveSince',
 'ModelVersion',
 'Rating',
 'Status',
 'Restructured',
 'WorseLateCategory',
 'CreditScoreEsMicroL',
 'CreditScoreEeMini',
 'PrincipalPaymentsMade',
 'InterestAndPenaltyPaymentsMade',
 'PrincipalBalance',
 'InterestAndPenaltyBalance',
 'NoOfPreviousLoansBeforeLoan',
 'AmountOfPreviousLoansBeforeLoan',
 'PreviousRepaymentsBeforeLoan',
 'PreviousEarlyRepaymentsCountBeforeLoan',
 'NextPaymentNr',
 'NrOfScheduledPayments']

In [197]:
# Check the types of data we have in the dataset in each column
dataset.dtypes

ReportAsOfEOD                              object
LoanId                                     object
LoanNumber                                  int64
ListedOnUTC                                object
BiddingStartedOn                           object
                                           ...
AmountOfPreviousLoansBeforeLoan           float64
PreviousRepaymentsBeforeLoan              float64
PreviousEarlyRepaymentsCountBeforeLoan    float64
NextPaymentNr                             float64
NrOfScheduledPayments                     float64
Length: 76, dtype: object

In [198]:
# After analysing the dataset, 
# We can see that the following columns are not useful for our analysis and can be dropped

#Create a variable having these columns and the length of the variable
drop = ['ReportAsOfEOD',
        'LoanId',
        'LoanNumber',
        'ListedOnUTC',
        'BiddingStartedOn',
        'UserName', 
        'LanguageCode',
        'LoanApplicationStartedDate',
        'IncomeFromPrincipalEmployer', 
        'IncomeFromPension',
        'IncomeFromFamilyAllowance', 
        'IncomeFromSocialWelfare',
        'IncomeFromLeavePay', 
        'IncomeFromChildSupport', 
        'IncomeOther',
        'LoanApplicationStartedDate',
        'ApplicationSignedHour',
        'ApplicationSignedWeekday',
        'ActiveScheduleFirstPaymentReached',
        'ModelVersion',
        'WorseLateCategory',
        'NextPaymentNr',
        'ProbabilityOfDefault',
        'NrOfScheduledPayments',
        'LossGivenDefault',
        'LoanDate']

print(len(drop))

26

In [199]:
#Drop columns from the variable created above
dataset = dataset.drop(drop, axis=1)

In [200]:
dataset

,BidsPortfolioManager,BidsApi,BidsManual,NewCreditCustomer,ContractEndDate,FirstPaymentDate,MaturityDate_Original,MaturityDate_Last,VerificationType,Age,...,CreditScoreEsMicroL,CreditScoreEeMini,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan
0,970,1150,5.0,False,2020-06-26,2016-05-12,2021-04-12,2020-06-26,4.0,53,...,NaN,1000.0,969.16,1187.91,1155.84,433.60,1.0,500.0,590.95,0.0
1,1295,0,1705.0,False,NaN,2015-08-17,2020-07-17,2020-07-17,1.0,50,...,NaN,1000.0,563.59,360.07,2436.41,2291.82,1.0,1800.0,445.26,1.0
2,2700,565,5835.0,True,2019-10-24,2016-02-22,2021-01-20,2021-01-20,4.0,44,...,NaN,1000.0,6537.00,1708.47,0.00,0.00,0.0,0.0,0.00,0.0
3,1115,0,385.0,True,NaN,2015-05-04,2020-04-01,2020-04-01,3.0,42,...,M3,NaN,464.73,355.92,1035.27,2833.83,0.0,0.0,0.00,1.0
4,305,0,785.0,True,NaN,2016-02-01,2020-01-02,2020-01-02,4.0,34,...,M5,NaN,0.01,0.00,1089.99,4215.37,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179230,2000,0,0.0,True,NaN,2015-04-15,2020-03-16,2020-03-16,1.0,38,...,NaN,NaN,0.00,0.00,2000.00,4284.86,0.0,0.0,0.00,0.0
179231,6215,70,1155.0,False,2017-09-19,2016-03-23,2021-02-23,2021-02-23,4.0,37,...,NaN,NaN,7440.00,2664.67,0.00,0.00,2.0,2500.0,986.78,0.0
179232,430,0,1055.0,False,2016-04-21,2016-04-01,2021-03-01,2021-03-01,1.0,37,...,M4,NaN,1485.00,186.41,0.00,0.00,3.0,2425.0,2749.65,1.0
179233,3000,0,0.0,True,2020-09-10,2015-10-12,2020-09-10,2020-09-10,1.0,58,...,NaN,1000.0,3000.00,1974.70,0.00,0.00,0.0,0.0,0.00,0.0
179234,0,0,1300.0,False,2017-12-18,2015-07-20,2019-06-20,2021-04-01,4.0,64,...,NaN,1000.0,475.78,152.98,0.00,0.00,4.0,8000.0,4462.13,2.0

In [201]:
#Get column names that are still present in the dataset
columns = list(dataset.columns.values)
columns

['BidsPortfolioManager',
 'BidsApi',
 'BidsManual',
 'NewCreditCustomer',
 'ContractEndDate',
 'FirstPaymentDate',
 'MaturityDate_Original',
 'MaturityDate_Last',
 'VerificationType',
 'Age',
 'Gender',
 'Country',
 'AppliedAmount',
 'Amount',
 'Interest',
 'LoanDuration',
 'MonthlyPayment',
 'UseOfLoan',
 'Education',
 'MaritalStatus',
 'EmploymentStatus',
 'EmploymentDurationCurrentEmployer',
 'OccupationArea',
 'HomeOwnershipType',
 'IncomeTotal',
 'ExistingLiabilities',
 'LiabilitiesTotal',
 'RefinanceLiabilities',
 'DebtToIncome',
 'FreeCash',
 'MonthlyPaymentDay',
 'PlannedInterestTillDate',
 'LastPaymentOn',
 'ExpectedLoss',
 'ExpectedReturn',
 'PrincipalOverdueBySchedule',
 'RecoveryStage',
 'StageActiveSince',
 'Rating',
 'Status',
 'Restructured',
 'CreditScoreEsMicroL',
 'CreditScoreEeMini',
 'PrincipalPaymentsMade',
 'InterestAndPenaltyPaymentsMade',
 'PrincipalBalance',
 'InterestAndPenaltyBalance',
 'NoOfPreviousLoansBeforeLoan',
 'AmountOfPreviousLoansBeforeLoan',
 'PreviousRepaymentsBeforeLoan',
 'PreviousEarlyRepaymentsCountBeforeLoan']

In [202]:
# Check the types of data we have in the dataset in each column
dataset.dtypes

BidsPortfolioManager                        int64
BidsApi                                     int64
BidsManual                                float64
NewCreditCustomer                            bool
ContractEndDate                            object
FirstPaymentDate                           object
MaturityDate_Original                      object
MaturityDate_Last                          object
VerificationType                          float64
Age                                         int64
Gender                                    float64
Country                                    object
AppliedAmount                             float64
Amount                                    float64
Interest                                  float64
LoanDuration                                int64
MonthlyPayment                            float64
UseOfLoan                                   int64
Education                                 float64
MaritalStatus                             float64
EmploymentStatus                          float64
EmploymentDurationCurrentEmployer          object
OccupationArea                            float64
HomeOwnershipType                         float64
IncomeTotal                               float64
ExistingLiabilities                         int64
LiabilitiesTotal                          float64
RefinanceLiabilities                        int64
DebtToIncome                              float64
FreeCash                                  float64
MonthlyPaymentDay                           int64
PlannedInterestTillDate                   float64
LastPaymentOn                              object
ExpectedLoss                              float64
ExpectedReturn                            float64
PrincipalOverdueBySchedule                float64
RecoveryStage                             float64
StageActiveSince                           object
Rating                                     object
Status                                     object
Restructured                                 bool
CreditScoreEsMicroL                        object
CreditScoreEeMini                         float64
PrincipalPaymentsMade                     float64
InterestAndPenaltyPaymentsMade            float64
PrincipalBalance                          float64
InterestAndPenaltyBalance                 float64
NoOfPreviousLoansBeforeLoan               float64
AmountOfPreviousLoansBeforeLoan           float64
PreviousRepaymentsBeforeLoan              float64
PreviousEarlyRepaymentsCountBeforeLoan    float64
dtype: object

In [203]:
clean=dataset
clean

,BidsPortfolioManager,BidsApi,BidsManual,NewCreditCustomer,ContractEndDate,FirstPaymentDate,MaturityDate_Original,MaturityDate_Last,VerificationType,Age,...,CreditScoreEsMicroL,CreditScoreEeMini,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan
0,970,1150,5.0,False,2020-06-26,2016-05-12,2021-04-12,2020-06-26,4.0,53,...,NaN,1000.0,969.16,1187.91,1155.84,433.60,1.0,500.0,590.95,0.0
1,1295,0,1705.0,False,NaN,2015-08-17,2020-07-17,2020-07-17,1.0,50,...,NaN,1000.0,563.59,360.07,2436.41,2291.82,1.0,1800.0,445.26,1.0
2,2700,565,5835.0,True,2019-10-24,2016-02-22,2021-01-20,2021-01-20,4.0,44,...,NaN,1000.0,6537.00,1708.47,0.00,0.00,0.0,0.0,0.00,0.0
3,1115,0,385.0,True,NaN,2015-05-04,2020-04-01,2020-04-01,3.0,42,...,M3,NaN,464.73,355.92,1035.27,2833.83,0.0,0.0,0.00,1.0
4,305,0,785.0,True,NaN,2016-02-01,2020-01-02,2020-01-02,4.0,34,...,M5,NaN,0.01,0.00,1089.99,4215.37,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179230,2000,0,0.0,True,NaN,2015-04-15,2020-03-16,2020-03-16,1.0,38,...,NaN,NaN,0.00,0.00,2000.00,4284.86,0.0,0.0,0.00,0.0
179231,6215,70,1155.0,False,2017-09-19,2016-03-23,2021-02-23,2021-02-23,4.0,37,...,NaN,NaN,7440.00,2664.67,0.00,0.00,2.0,2500.0,986.78,0.0
179232,430,0,1055.0,False,2016-04-21,2016-04-01,2021-03-01,2021-03-01,1.0,37,...,M4,NaN,1485.00,186.41,0.00,0.00,3.0,2425.0,2749.65,1.0
179233,3000,0,0.0,True,2020-09-10,2015-10-12,2020-09-10,2020-09-10,1.0,58,...,NaN,1000.0,3000.00,1974.70,0.00,0.00,0.0,0.0,0.00,0.0
179234,0,0,1300.0,False,2017-12-18,2015-07-20,2019-06-20,2021-04-01,4.0,64,...,NaN,1000.0,475.78,152.98,0.00,0.00,4.0,8000.0,4462.13,2.0

In [204]:
# Save new dataset to csv as Clean_Loan_Bondora.csv
clean.to_csv('Clean_Loan_Bondora.csv', index=False)

BidsPortfolioManager,
BidsApi,
BidsManual,
NewCreditCustomer,
ContractEndDate,
FirstPaymentDate,
MaturityDate_Original,
MaturityDate_Last,
VerificationType,
Age,
Gender,
Country,
AppliedAmount,
Amount,
Interest,
LoanDuration,
MonthlyPayment,
UseOfLoan,
Education,
MaritalStatus,
EmploymentStatus,
EmploymentDurationCurrentEmployer,
OccupationArea,
HomeOwnershipType,
IncomeTotal,
ExistingLiabilities,
LiabilitiesTotal,
RefinanceLiabilities,
DebtToIncome,
FreeCash,
MonthlyPaymentDay,
PlannedInterestTillDate,
LastPaymentOn,
ExpectedLoss,
ExpectedReturn,
PrincipalOverdueBySchedule,
RecoveryStage,
StageActiveSince,
Rating,
Status,
Restructured,
CreditScoreEsMicroL,
CreditScoreEeMini,
PrincipalPaymentsMade,
InterestAndPenaltyPaymentsMade,
PrincipalBalance,
InterestAndPenaltyBalance,
NoOfPreviousLoansBeforeLoan,
AmountOfPreviousLoansBeforeLoan,
PreviousRepaymentsBeforeLoan,
PreviousEarlyRepaymentsCountBeforeLoan

In [205]:
# Create an Object type Encoder to encode the object type columns present in the dataset
from sklearn.preprocessing import LabelEncoder
encodeObject = LabelEncoder()
countEncodes = 0
for col in dataset.columns[1:]:
    if dataset[col].dtype == 'object':
        encodeObject.fit(dataset[col])
        dataset[col] = encodeObject.transform(dataset[col])
        countEncodes += 1

In [206]:
dataset

,BidsPortfolioManager,BidsApi,BidsManual,NewCreditCustomer,ContractEndDate,FirstPaymentDate,MaturityDate_Original,MaturityDate_Last,VerificationType,Age,...,CreditScoreEsMicroL,CreditScoreEeMini,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan
0,970,1150,5.0,False,2998,1271,2229,2260,4.0,53,...,11,1000.0,969.16,1187.91,1155.84,433.60,1.0,500.0,590.95,0.0
1,1295,0,1705.0,False,4670,1107,2058,2275,1.0,50,...,11,1000.0,563.59,360.07,2436.41,2291.82,1.0,1800.0,445.26,1.0
2,2700,565,5835.0,True,2753,1222,2176,2415,4.0,44,...,11,1000.0,6537.00,1708.47,0.00,0.00,0.0,0.0,0.00,0.0
3,1115,0,385.0,True,4670,1043,1987,2193,3.0,42,...,4,NaN,464.73,355.92,1035.27,2833.83,0.0,0.0,0.00,1.0
4,305,0,785.0,True,4670,1207,1930,2118,4.0,34,...,6,NaN,0.01,0.00,1089.99,4215.37,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179230,2000,0,0.0,True,4670,1034,1977,2182,1.0,38,...,11,NaN,0.00,0.00,2000.00,4284.86,0.0,0.0,0.00,0.0
179231,6215,70,1155.0,False,1996,1242,2198,2446,4.0,37,...,11,NaN,7440.00,2664.67,0.00,0.00,2.0,2500.0,986.78,0.0
179232,430,0,1055.0,False,1532,1245,2202,2451,1.0,37,...,5,NaN,1485.00,186.41,0.00,0.00,3.0,2425.0,2749.65,1.0
179233,3000,0,0.0,True,3074,1142,2091,2318,1.0,58,...,11,1000.0,3000.00,1974.70,0.00,0.00,0.0,0.0,0.00,0.0
179234,0,0,1300.0,False,2084,1091,1808,2478,4.0,64,...,11,1000.0,475.78,152.98,0.00,0.00,4.0,8000.0,4462.13,2.0

In [207]:
# Create a Boolean type Encoder to encode the bool type columns present in the dataset
encodeBool = LabelEncoder()
countEncodes = 0
for col in dataset.columns[1:]:
    if dataset[col].dtype == 'bool':
        encodeBool.fit(dataset[col])
        dataset[col] = encodeBool.transform(dataset[col])
        countEncodes += 1

To be easier to use the dataset we decided to encode all the boolean values to have a better uniformity in the data. Previously we encoded all the object values since there were many date type columns. Using the encoders we have managed to achieve a better and more uniform dataset.

In [208]:
dataset

,BidsPortfolioManager,BidsApi,BidsManual,NewCreditCustomer,ContractEndDate,FirstPaymentDate,MaturityDate_Original,MaturityDate_Last,VerificationType,Age,...,CreditScoreEsMicroL,CreditScoreEeMini,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan
0,970,1150,5.0,0,2998,1271,2229,2260,4.0,53,...,11,1000.0,969.16,1187.91,1155.84,433.60,1.0,500.0,590.95,0.0
1,1295,0,1705.0,0,4670,1107,2058,2275,1.0,50,...,11,1000.0,563.59,360.07,2436.41,2291.82,1.0,1800.0,445.26,1.0
2,2700,565,5835.0,1,2753,1222,2176,2415,4.0,44,...,11,1000.0,6537.00,1708.47,0.00,0.00,0.0,0.0,0.00,0.0
3,1115,0,385.0,1,4670,1043,1987,2193,3.0,42,...,4,NaN,464.73,355.92,1035.27,2833.83,0.0,0.0,0.00,1.0
4,305,0,785.0,1,4670,1207,1930,2118,4.0,34,...,6,NaN,0.01,0.00,1089.99,4215.37,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179230,2000,0,0.0,1,4670,1034,1977,2182,1.0,38,...,11,NaN,0.00,0.00,2000.00,4284.86,0.0,0.0,0.00,0.0
179231,6215,70,1155.0,0,1996,1242,2198,2446,4.0,37,...,11,NaN,7440.00,2664.67,0.00,0.00,2.0,2500.0,986.78,0.0
179232,430,0,1055.0,0,1532,1245,2202,2451,1.0,37,...,5,NaN,1485.00,186.41,0.00,0.00,3.0,2425.0,2749.65,1.0
179233,3000,0,0.0,1,3074,1142,2091,2318,1.0,58,...,11,1000.0,3000.00,1974.70,0.00,0.00,0.0,0.0,0.00,0.0
179234,0,0,1300.0,0,2084,1091,1808,2478,4.0,64,...,11,1000.0,475.78,152.98,0.00,0.00,4.0,8000.0,4462.13,2.0

In [209]:
dataset.dtypes

BidsPortfolioManager                        int64
BidsApi                                     int64
BidsManual                                float64
NewCreditCustomer                           int64
ContractEndDate                             int64
FirstPaymentDate                            int64
MaturityDate_Original                       int64
MaturityDate_Last                           int64
VerificationType                          float64
Age                                         int64
Gender                                    float64
Country                                     int64
AppliedAmount                             float64
Amount                                    float64
Interest                                  float64
LoanDuration                                int64
MonthlyPayment                            float64
UseOfLoan                                   int64
Education                                 float64
MaritalStatus                             float64
EmploymentStatus                          float64
EmploymentDurationCurrentEmployer           int64
OccupationArea                            float64
HomeOwnershipType                         float64
IncomeTotal                               float64
ExistingLiabilities                         int64
LiabilitiesTotal                          float64
RefinanceLiabilities                        int64
DebtToIncome                              float64
FreeCash                                  float64
MonthlyPaymentDay                           int64
PlannedInterestTillDate                   float64
LastPaymentOn                               int64
ExpectedLoss                              float64
ExpectedReturn                            float64
PrincipalOverdueBySchedule                float64
RecoveryStage                             float64
StageActiveSince                            int64
Rating                                      int64
Status                                      int64
Restructured                                int64
CreditScoreEsMicroL                         int64
CreditScoreEeMini                         float64
PrincipalPaymentsMade                     float64
InterestAndPenaltyPaymentsMade            float64
PrincipalBalance                          float64
InterestAndPenaltyBalance                 float64
NoOfPreviousLoansBeforeLoan               float64
AmountOfPreviousLoansBeforeLoan           float64
PreviousRepaymentsBeforeLoan              float64
PreviousEarlyRepaymentsCountBeforeLoan    float64
dtype: object

In [210]:
#Fill all the nan values with the median value in each column
dataset = dataset.fillna(dataset.median())

In [211]:
#Pass all float64 to int64
for col in dataset.columns[1:]:
    if dataset[col].dtype == 'float64':
        dataset[col] = dataset[col].astype('int64')

In [212]:
#Count nan values in all columns
for i in dataset.columns:
    print(i,dataset[i].isnull().sum())

BidsPortfolioManager 0
BidsApi 0
BidsManual 0
NewCreditCustomer 0
ContractEndDate 0
FirstPaymentDate 0
MaturityDate_Original 0
MaturityDate_Last 0
VerificationType 0
Age 0
Gender 0
Country 0
AppliedAmount 0
Amount 0
Interest 0
LoanDuration 0
MonthlyPayment 0
UseOfLoan 0
Education 0
MaritalStatus 0
EmploymentStatus 0
EmploymentDurationCurrentEmployer 0
OccupationArea 0
HomeOwnershipType 0
IncomeTotal 0
ExistingLiabilities 0
LiabilitiesTotal 0
RefinanceLiabilities 0
DebtToIncome 0
FreeCash 0
MonthlyPaymentDay 0
PlannedInterestTillDate 0
LastPaymentOn 0
ExpectedLoss 0
ExpectedReturn 0
PrincipalOverdueBySchedule 0
RecoveryStage 0
StageActiveSince 0
Rating 0
Status 0
Restructured 0
CreditScoreEsMicroL 0
CreditScoreEeMini 0
PrincipalPaymentsMade 0
InterestAndPenaltyPaymentsMade 0
PrincipalBalance 0
InterestAndPenaltyBalance 0
NoOfPreviousLoansBeforeLoan 0
AmountOfPreviousLoansBeforeLoan 0
PreviousRepaymentsBeforeLoan 0
PreviousEarlyRepaymentsCountBeforeLoan 0

With this step we can now check that we have all the data encoded and that there are no missing values after the use of the KNN imputer to complete the dataset

In [213]:
newdataset = dataset
newdataset

,BidsPortfolioManager,BidsApi,BidsManual,NewCreditCustomer,ContractEndDate,FirstPaymentDate,MaturityDate_Original,MaturityDate_Last,VerificationType,Age,...,CreditScoreEsMicroL,CreditScoreEeMini,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan
0,970,1150,5,0,2998,1271,2229,2260,4,53,...,11,1000,969,1187,1155,433,1,500,590,0
1,1295,0,1705,0,4670,1107,2058,2275,1,50,...,11,1000,563,360,2436,2291,1,1800,445,1
2,2700,565,5835,1,2753,1222,2176,2415,4,44,...,11,1000,6537,1708,0,0,0,0,0,0
3,1115,0,385,1,4670,1043,1987,2193,3,42,...,4,1000,464,355,1035,2833,0,0,0,1
4,305,0,785,1,4670,1207,1930,2118,4,34,...,6,1000,0,0,1089,4215,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179230,2000,0,0,1,4670,1034,1977,2182,1,38,...,11,1000,0,0,2000,4284,0,0,0,0
179231,6215,70,1155,0,1996,1242,2198,2446,4,37,...,11,1000,7440,2664,0,0,2,2500,986,0
179232,430,0,1055,0,1532,1245,2202,2451,1,37,...,5,1000,1485,186,0,0,3,2425,2749,1
179233,3000,0,0,1,3074,1142,2091,2318,1,58,...,11,1000,3000,1974,0,0,0,0,0,0
179234,0,0,1300,0,2084,1091,1808,2478,4,64,...,11,1000,475,152,0,0,4,8000,4462,2

In [214]:
#Save the new dataset to csv as Full_Bondora.csv
newdataset.to_csv('Full_Bondora.csv', index=False)

In [218]:
#Data Description
dataset.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
BidsPortfolioManager,179235.0,797.962530,1235.509764,0.0,105.0,336.0,960.0,10625.0
BidsApi,179235.0,27.432337,147.568318,0.0,0.0,0.0,4.0,7570.0
BidsManual,179235.0,499.539024,714.726007,0.0,50.0,258.0,639.0,10630.0
NewCreditCustomer,179235.0,0.560170,0.496368,0.0,0.0,1.0,1.0,1.0
ContractEndDate,179235.0,3881.544358,1012.647136,0.0,3172.0,4348.0,4670.0,4670.0
FirstPaymentDate,179235.0,1848.817485,460.596984,0.0,1626.0,1982.0,2129.0,2476.0
MaturityDate_Original,179235.0,2572.113789,611.675783,0.0,2229.0,2635.0,3026.0,3441.0
MaturityDate_Last,179235.0,2935.947778,722.234442,0.0,2566.0,3131.0,3472.0,3936.0
VerificationType,179235.0,3.043669,1.352410,0.0,1.0,4.0,4.0,4.0
Age,179235.0,40.389137,12.359547,0.0,31.0,39.0,49.0,77.0
Gender,179235.0,0.466683,0.620325,0.0,0.0,0.0,1.0,2.0
Country,179235.0,0.619678,0.844835,0.0,0.0,0.0,1.0,3.0
AppliedAmount,179235.0,2699.119374,2342.766044,10.0,740.0,2125.0,4150.0,10632.0
Amount,179235.0,2543.464301,2182.072205,6.0,740.0,2125.0,3825.0,10632.0
Interest,179235.0,33.870371,23.775249,2.0,19.0,30.0,39.0,264.0
LoanDuration,179235.0,47.324747,15.370251,1.0,36.0,60.0,60.0,60.0
MonthlyPayment,179235.0,111.567674,105.592370,0.0,34.0,90.0,148.0,2368.0
UseOfLoan,179235.0,0.008213,2.927697,-1.0,-1.0,-1.0,-1.0,110.0
Education,179235.0,3.589500,1.242101,-1.0,3.0,4.0,4.0,5.0
MaritalStatus,179235.0,-0.331587,1.401395,-1.0,-1.0,-1.0,-1.0,5.0
EmploymentStatus,179235.0,-0.135320,1.752806,-1.0,-1.0,-1.0,-1.0,6.0
EmploymentDurationCurrentEmployer,179235.0,3.398388,3.263942,0.0,0.0,4.0,7.0,9.0
OccupationArea,179235.0,0.786504,4.350507,-1.0,-1.0,-1.0,-1.0,19.0
HomeOwnershipType,179235.0,3.306670,2.885529,-1.0,1.0,2.0,3.0,10.0
IncomeTotal,179235.0,1763.365676,8127.175976,0.0,874.0,1230.0,1900.0,1012019.0
ExistingLiabilities,179235.0,2.937562,3.264559,0.0,1.0,2.0,4.0,40.0
LiabilitiesTotal,179235.0,490.653405,29324.562038,0.0,49.0,272.0,555.0,12400000.0
RefinanceLiabilities,179235.0,0.140592,0.780866,0.0,0.0,0.0,0.0,23.0
DebtToIncome,179235.0,5.734644,14.317934,0.0,0.0,0.0,0.0,198.0
FreeCash,179235.0,91.645320,602.116823,-2332.0,0.0,0.0,0.0,158748.0
MonthlyPaymentDay,179235.0,11.154261,6.801899,0.0,5.0,11.0,15.0,28.0
PlannedInterestTillDate,179235.0,977.752124,1471.584944,0.0,98.0,444.0,1183.0,18054.0
LastPaymentOn,179235.0,3008.884805,623.280110,0.0,2835.0,3346.0,3411.0,3422.0
ExpectedLoss,179235.0,0.000006,0.002362,0.0,0.0,0.0,0.0,1.0
ExpectedReturn,179235.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
PrincipalOverdueBySchedule,179235.0,303.395319,825.734286,0.0,0.0,0.0,185.0,10630.0
RecoveryStage,179235.0,1.689307,0.462778,1.0,1.0,2.0,2.0,2.0
StageActiveSince,179235.0,43014.889162,21482.773711,0.0,26176.5,47388.0,64708.0,64708.0
Rating,179235.0,4.079572,1.845795,0.0,3.0,4.0,5.0,8.0
Status,179235.0,0.972734,0.785282,0.0,0.0,1.0,2.0,2.0
Restructured,179235.0,0.312484,0.463507,0.0,0.0,0.0,1.0,1.0
CreditScoreEsMicroL,179235.0,2.108416,4.151797,0.0,0.0,0.0,0.0,11.0
CreditScoreEeMini,179235.0,969.038413,86.969200,0.0,1000.0,1000.0,1000.0,1000.0
PrincipalPaymentsMade,179235.0,972.241789,1474.429146,0.0,110.0,426.0,1156.0,10632.0
InterestAndPenaltyPaymentsMade,179235.0,598.641644,957.046675,0.0,68.0,246.0,740.0,18393.0
PrincipalBalance,179235.0,1543.830268,1937.867620,-34.0,0.0,716.0,2285.0,10632.0
InterestAndPenaltyBalance,179235.0,911.797713,2926.854866,-2.0,0.0,0.0,466.0,78982.0
NoOfPreviousLoansBeforeLoan,179235.0,1.575568,2.520343,0.0,0.0,1.0,2.0,27.0
AmountOfPreviousLoansBeforeLoan,179235.0,3129.438056,4887.193843,0.0,0.0,530.0,4253.0,72778.0
PreviousRepaymentsBeforeLoan,179235.0,735.039345,1614.043739,0.0,142.0,279.0,512.0,34077.0
PreviousEarlyRepaymentsCountBeforeLoan,179235.0,0.062683,0.340699,0.0,0.0,0.0,0.0,11.0

With this we can now visualize a little bit better more information about the whole dataset and with the transpose we can observe a little bit better everything unlike the normal describe function where each column is a new feature taking up more space.